### ISSUE TITLE
Como é que fizeste isso?

### ISSUE THREAD

**Issue by e200** [doriel/sapo-ao-logo#1]

**Comment by doriel** [comment]
@e200 com a propriedade "clip-path"...

**Comment by e200** [comment]
. Essa Propriedade Faz Parte De Algum Software?

**Comment by doriel** [comment]
@e200 não é mesmo do Css3....

**Comment by e200** [comment]
. O Que Eu Estou Mesmo a Tentar Perceber é Como Fizeste o Logotipo Com HTML e CSS? Na Mão Mesmo, Div Por Div, Etc... Ou Usaste Algum Tipo De Ferramente Como Illustrator e Depois Vectorizaste?

**Comment by doriel** [comment]
Div por div, só tens de ter paciência... @e200 no [Codepen](http://codepen.io/)  tem muitos "projectos" semelhantes e mais difíceis...

**Comment by doriel** [comment]
@e200 Saiba que isso é também um bom desafio para melhorar os "SKILLS" em CSS...

**Comment by e200** [comment]
. **Thank You Man**, I'll Make It a New Hobby!

**Comment by doriel** [comment]
@e200 Nice...

**Comment by JoseCage** [comment]
Awesome project @doriel 🙉
